Repository dappforce/dappforce-subsocial-ui, pull requests merged in 2020-05, with the labels that each got.

#189 Use Markdown CSS from GitHub for rendered markdown
  src/components/utils/DfMd.tsx
  src/components/utils/styles/github-markdown.css
Labels: enhancement

#197 Create About Blog page: SRR + link in a space nav
  src/components/blogs/AboutBlog.tsx
  src/components/blogs/BlogStatsRow.tsx
  src/components/blogs/BloggedSectionTitle.tsx
  src/components/blogs/ListAllBlogs.tsx
  src/components/blogs/ListBlogs.tsx
  src/components/blogs/ListFollowingBlogs.tsx
  src/components/blogs/ListMyBlogs.tsx
  src/components/blogs/SpaceNav.tsx
  src/components/blogs/ViewBlog.tsx
  src/components/blogs/ViewBlogProps.ts
  src/components/blogs/withLoadBlogDataById.tsx
  src/components/profiles/EditProfile.tsx
  src/components/profiles/ViewProfile.tsx
  src/components/profiles/address-views/ProfilePreview.tsx
  src/components/profiles/address-views/utils/NameDetails.tsx
  src/components/utils/FollowAccountButton.tsx
  src/components/utils/MyEntityLabel.tsx
  src/components/utils/ViewTags.tsx
  src/components/utils/index.tsx
  src/components/utils/next.ts
  src/components/utils/styles/subsocial-mobile.css
  src/components/utils/styles/subsocial.css
  src/components/utils/urls.ts
  src/pages/blogs/[blogId]/about.tsx
  src/pages/blogs/all.tsx
  src/pages/blogs/my/[address].tsx
Labels: enhancement

#204 Add Share button to View Post page
  src/components/posts/ShareModal.tsx
  src/components/posts/SharePostAction.tsx
  src/components/posts/ViewPost.tsx
  src/components/utils/styles/subsocial.css
Labels: ux

#213 Refactor feed and notifications after Comments v2
  package.json
  src/components/activity/MyFeed.tsx
  src/components/activity/Notification.tsx
  src/components/activity/NotificationUtils.tsx
  src/components/blogs/ViewBlog.tsx
  src/components/main/HomePage.tsx
  src/components/main/LatestPosts.tsx
  src/components/posts/CommentTree.tsx
  src/components/posts/CommentsSection.tsx
  src/components/posts/OldEditComment.tsx
  src/components/posts/OldViewComment.tsx
  src/components/posts/PostPreview.tsx
  src/components/posts/PostPreviewList.tsx
  src/components/posts/ViewPost.tsx
  src/components/utils/Api.tsx
  src/components/utils/utils.tsx
  src/components/voting/Voter.tsx
  src/layout/ClientLayout.tsx
  yarn.lock
Labels: refactoring
