Repository dappforce/dappforce-subsocial-ui, pull requests merged in 2020-11, with the labels that each got.

#350 Refactor search
  export-env.js
  localhost.env
  package.json
  src/components/activity/InnerActivities.tsx
  src/components/activity/NotificationUtils.tsx
  src/components/activity/types.ts
  src/components/lists/DataList.tsx
  src/components/lists/InfiniteList.tsx
  src/components/posts/PostPreviewList.tsx
  src/components/posts/view-post/PostPreviewList.tsx
  src/components/search/Search.tsx
  src/components/search/SearchInput.tsx
  src/components/search/SearchResults.tsx
  src/components/spaces/NavigationEditor.tsx
  src/components/spaces/helpers/PostPreviewsOnSpace.tsx
  src/components/utils/OffchainUtils.ts
  src/components/utils/env.ts
  src/components/utils/getIds.ts
  src/config/ElasticConfig.ts
  src/layout/Navigation.tsx
  src/layout/TopMenu.tsx
  src/styles/subsocial.scss
  subsocial-betanet.env
Labels: refactoring

#354 Make possible to hide feed, notifications, account activity and search
  export-env.js
  localhost.env
  src/components/activity/AccountActivity.tsx
  src/components/main/HomePage.tsx
  src/components/utils/env.ts
  src/components/utils/index.tsx
  src/layout/SideMenuItems.tsx
  src/layout/TopMenu.tsx
  src/pages/feed.tsx
  src/pages/notifications.tsx
  src/pages/search.tsx
  subsocial-betanet.env
Labels: new feature

#356 Various improvements and refactoring
  export-env.js
  localhost.env
  package.json
  src/components/activity/AccountActivity.tsx
  src/components/activity/InnerActivities.tsx
  src/components/activity/Notification.tsx
  src/components/activity/NotificationUtils.tsx
  src/components/activity/Notifications.tsx
  src/components/main/HomePage.tsx
  src/components/profiles/ViewProfile.tsx
  src/components/profiles/address-views/utils/NameDetails.tsx
  src/components/search/SearchInput.tsx
  src/components/search/SearchResults.tsx
  src/components/spaces/NavigationEditor.ignore
  src/components/spaces/SocialLinks/NewSocialLinks.tsx
  src/components/spaces/SocialLinks/ViewSocialLinks.tsx
  src/components/spaces/SpaceStatsRow.tsx
  src/components/utils/EditableTagGroup.ignore
  src/components/utils/OffchainUtils.ts
  src/components/utils/SubsocialConnect.ts
  src/components/utils/content/index.ts
  src/components/utils/env.ts
  src/components/utils/forms/index.tsx
  src/components/utils/index.tsx
  src/layout/SideMenuItems.tsx
  src/layout/TopMenu.tsx
  src/pages/[spaceId]/space-navigation/edit.tsx
  src/pages/feed.tsx
  src/pages/notifications.tsx
  src/pages/search.tsx
  src/styles/antd.css
  src/styles/subsocial.scss
  subsocial-betanet.env
  tsconfig.json
  yarn.lock
Labels: refactoring

#363 Add sitemaps and canonical URLs
  export-env.js
  localhost.env
  package.json
  src/components/activity/NotificationUtils.tsx
  src/components/comments/CommentsSection.tsx
  src/components/comments/ViewComment.tsx
  src/components/posts/EditPost.tsx
  src/components/posts/ViewPostLink.tsx
  src/components/posts/share/ShareDropdown/index.tsx
  src/components/posts/slugify.ts
  src/components/posts/view-post/PostPage.tsx
  src/components/posts/view-post/ViewSharedPreview.tsx
  src/components/posts/view-post/helpers.tsx
  src/components/sitemap/index.ts
  src/components/spaces/ViewSpace.tsx
  src/components/substrate/util/index.ts
  src/components/urls/helpers.tsx
  src/components/urls/subsocial.ts
  src/components/utils/Faucet/Step1.tsx
  src/components/utils/HeadMeta.tsx
  src/components/utils/env.ts
  src/components/utils/getIds.ts
  src/components/utils/index.tsx
  src/components/utils/md/SummarizeMd.tsx
  src/pages/[spaceId]/[slug]/edit.tsx
  src/pages/[spaceId]/[slug]/index.tsx
  src/pages/[spaceId]/posts/[postId]/edit.tsx
  src/pages/[spaceId]/posts/[postId]/index.tsx
  src/pages/robots.txt.tsx
  src/pages/sitemap.xml.ts
  src/pages/sitemaps/[page]/posts.xml.ts
  src/pages/sitemaps/[page]/spaces.xml.ts
  src/pages/sitemaps/posts.xml.ts
  src/pages/sitemaps/profiles.xml.ts
  src/pages/sitemaps/spaces.xml.ts
  src/redux/slices/postByIdSlice.ts
  src/utils/text.ts
  subsocial-betanet.env
  yarn.lock
Labels: new feature

#373 Show "Create space" or "New post" button in top menu
  src/components/auth/AuthorizationPanel.tsx
  src/components/auth/OnlySudo.tsx
  src/components/main/PageWrapper.tsx
  src/components/posts/NewPostButtonInTopMenu.module.sass
  src/components/posts/NewPostButtonInTopMenu.tsx
  src/components/profiles/EditProfile.tsx
  src/components/spaces/EditSpace.tsx
  src/components/spaces/helpers/common.tsx
  src/components/urls/goToPage.ts
  src/components/urls/helpers.tsx
  src/components/urls/social-share.ts
  src/styles/subsocial.scss
  src/utils/hacks.ts
Labels: ux

#377 Fix infinite loading of account spaces and empty social links
  src/components/spaces/AboutSpace.tsx
  src/components/spaces/AccountSpaces.tsx
Labels: needs review

#381 Fix redirects and previews
  src/components/main/PageWrapper.tsx
  src/components/posts/view-post/PostPage.tsx
  src/components/urls/helpers.tsx
Labels: bug, seo

#382 Add '$' for '*/new' and '*/edit' URLs in robots.txt
  src/pages/robots.txt.tsx
Labels: seo
