Repository dappforce/dappforce-subsocial-ui, pull requests merged in 2020-10, with the labels that each got.

#340 Refactor Auth feature and other changes
  src/components/auth/AuthContext.tsx
  src/components/auth/MyAccountContext.tsx
  src/components/auth/SignInModal.tsx
  src/components/main/HomePage.tsx
  src/components/posts/share/SpaceShareLink.tsx
  src/components/substrate/SubstrateTxButton.tsx
  src/components/utils/HeadMeta.tsx
  src/layout/Navigation.tsx
  src/layout/SideMenu.tsx
  src/stories/SignInModal.stories.tsx
Labels: refactoring

#338 Add Account Activities feature
  src/components/activity/AccountActivity.tsx
  src/components/activity/FeedActivities.tsx
  src/components/activity/InnerActivities.tsx
  src/components/activity/MyFeed.tsx
  src/components/activity/MyNotifications.tsx
  src/components/activity/Notification.tsx
  src/components/activity/NotificationUtils.tsx
  src/components/activity/Notifications.tsx
  src/components/activity/types.ts
  src/components/auth/AuthButtons.tsx
  src/components/lists/InfiniteList.tsx
  src/components/main/HomePage.tsx
  src/components/main/PageWrapper.tsx
  src/components/profiles/ViewProfile.tsx
  src/components/spaces/AccountSpaces.tsx
  src/components/utils/OffchainUtils.ts
  src/components/utils/SubsocialConnect.ts
  src/config/ListData.config.ts
  src/layout/TopMenu.tsx
  src/messages/index.ts
  src/pages/feed.tsx
  src/styles/subsocial.scss
  yarn.lock
Labels: new feature

#333 Use total count in infinite list
  src/components/activity/MyFeed.tsx
  src/components/activity/MyNotifications.tsx
  src/components/lists/InfiniteList.tsx
  src/components/utils/OffchainUtils.ts
Labels: refactoring

#345 Split space helpers
  src/components/posts/view-post/PostPage.tsx
  src/components/spaces/AccountSpaces.tsx
  src/components/spaces/ViewSpace.tsx
  src/components/spaces/helpers/AllSpacesLink.tsx
  src/components/spaces/helpers/CreatePostButton.tsx
  src/components/spaces/helpers/CreateSpaceButton.tsx
  src/components/spaces/helpers/DropdownMenu.tsx
  src/components/spaces/helpers/EditMenuLink.tsx
  src/components/spaces/helpers/PostPreviewsOnSpace.tsx
  src/components/spaces/helpers/SpaceAvatar.tsx
  src/components/spaces/helpers/common.tsx
  src/components/spaces/helpers/index.tsx
  src/components/spaces/helpers/useLoadUnlistedPostsByOwner.ts
  src/components/spaces/helpers/useLoadUnlistedSpace.tsx
Labels: refactoring

#343 Add SubsocialWarnPanel
  package.json
  src/components/auth/MyAccountContext.tsx
  src/components/utils/HiddenAlert/index.tsx
  src/components/utils/WarningPanel.tsx
  src/components/utils/WhereAmIPanel/index.module.sass
  src/components/utils/WhereAmIPanel/index.tsx
  src/components/utils/env.ts
  src/components/utils/index.tsx
  src/layout/MainPage.tsx
  yarn.lock
Labels: ux

#346 Transfer space ownership (new feature)
  src/components/auth/MyAccountContext.tsx
  src/components/comments/CreateComment.tsx
  src/components/forms/AntForms.tsx
  src/components/posts/view-post/PostPage.tsx
  src/components/posts/view-post/PostPreview.tsx
  src/components/posts/view-post/helpers.tsx
  src/components/profiles/ViewProfileLink.tsx
  src/components/profiles/address-views/Name.tsx
  src/components/profiles/address-views/ProfilePreview.tsx
  src/components/spaces/TransferSpaceOwnership.module.sass
  src/components/spaces/TransferSpaceOwnership.tsx
  src/components/spaces/ViewSpace.tsx
  src/components/spaces/helpers/CreatePostButton.tsx
  src/components/spaces/helpers/DropdownMenu.tsx
  src/components/spaces/helpers/common.tsx
  src/components/substrate/util/index.ts
  src/components/utils/EntityStatusPanels/EntityStatusPanel.tsx
  src/components/utils/EntityStatusPanels/HiddenEntityPanel.tsx
  src/components/utils/EntityStatusPanels/PendingSpaceOwnershipPanel.tsx
  src/components/utils/EntityStatusPanels/index.module.sass
  src/components/utils/EntityStatusPanels/index.tsx
  src/components/utils/HiddenAlert/index.module.sass
  src/components/utils/HiddenAlert/index.tsx
  src/components/utils/HiddenButton/index.module.sass
  src/components/utils/HiddenButton/index.tsx
  src/components/utils/WarningPanel.tsx
  src/components/utils/WhereAmIPanel/index.module.sass
  src/components/utils/WhereAmIPanel/index.tsx
  src/layout/TopMenu.tsx
  src/pages/sudo/forceTransfer.tsx
  src/styles/subsocial-vars.scss
  src/styles/subsocial.scss
Labels: new feature
